### ISSUE TITLE
BUG Error in versioning if renaming parent folder

### ISSUE THREAD

**Issue by tractorcow** [silverstripe-australia/silverstripe-versionedfiles#43]
As demonstrated by running FolderTest in framework, if you rename a parent folder, the resulting `FileVersion::saveCurrentVersion()` call will fail with the error `"Unable to save version #$version of file #$this->FileID."`

This is because the parent folder is renamed before this is invoked, and `$this->File()->getFullPath()` won't point to the actual file location until after it has been updated.

Perhaps in this case, a new file version shouldn't be created?

**Comment by nglasl** [comment]
May I ask, how are you encountering this issue, and would it only happen to be **3.2**? I'm running up a **3.1** instance to replicate the problem, and both renaming a parent folder, and running up the **FolderTest** seem to work okay..

`OK (17 tests, 55 assertions)`

**Comment by tractorcow** [comment]
It looks as though it's only occurring in 3.2 (for some reason). Perhaps you could shed some light on where the regression lies?

**Comment by nglasl** [comment]
That is interesting. I'm not too familiar with the **3.2** changes at present, so probably wouldn't be too much help at the moment. Any thoughts on why this might be falling through, @nyeholt?

**Comment by tractorcow** [comment]
Could it be related to https://github.com/silverstripe/silverstripe-framework/commit/dd0e2dc36200e3931923693c2b9dc978aea99825 at all? Note the File::exists change would affect Folder as well.

**Comment by tractorcow** [comment]
I think I found the problem... File::getRelativePath() uses $p->exists() to check for parent when it should be using $p->IsInDB(). ->exists() will return false if renaming, but the the underlying folder hasn't been renamed yet.

**Comment by tractorcow** [comment]
Proper fix at #57
